import imports
from pydantic import BaseModel, Field
from State_definition import AgentState
from test_runner import run_code_tests


class TestSuiteGeneration(BaseModel):
    test_plan: str = Field(
        description="A concise summary of what acceptance criteria and edge cases are being tested."
    )
    test_file_name: str = Field(
        default="test_verification.py",
        description="The relative filename for the test suite, e.g. test_verification.py"
    )
    test_file_content: str = Field(
        description="Complete, valid Python code implementing unit tests using unittest or pytest."
    )


def Test_Agent(state: AgentState) -> dict:
    """
    Test Agent (Stage 4):
    1. Consumes requirements, design, and the code artifact generated by the Code Agent.
    2. Autonomously generates independent verification unit tests based on acceptance criteria and design edge cases.
    3. Executes the test suite in a sandboxed, security-isolated runner tool (test_runner.py).
    4. Evaluates the execution outcome (pass/fail/errors) and stores structured metrics in state['test_results'].
    """
    print("\nTest Agent received code artifact for testing.")

    requirements = state.get("requirements", {})
    design = state.get("design", {})
    code_artifact = state.get("code", {})
    code_files = code_artifact.get("files", {})

    if not code_files:
        print("Warning: No code files provided to Test Agent.")
        return {
            "test_results": {
                "success": False,
                "total_tests": 0,
                "passed_tests": 0,
                "failed_tests": 0,
                "errors": ["No code files available in state['code']['files'] to execute tests against."],
                "raw_output": "Execution skipped: empty code artifact.",
                "summary": "Testing failed: Code Agent did not produce any source files.",
                "duration_seconds": 0.0,
                "test_files": {},
            },
            "test_version": state.get("test_version", 0) + 1,
            "current_stage": "test",
            "workflow_status": "running"
        }

    # 1. Initialize LLM
    llm = imports.get_llm(max_tokens=2000)

    test_generator_llm = llm.with_structured_output(
        TestSuiteGeneration,
        method="json_schema"
    )

    # 2. System prompt enforcing independent test generation
    system_prompt = imports.SystemMessage(
        content="""
You are an independent Quality Assurance and Test Engineering Agent.

Your responsibility is to write comprehensive, objective unit/integration tests
for the software code produced by the Code Agent.

You must:
1. Examine the Requirements (acceptance criteria, functional requirements, user stories).
2. Examine the Design (components, data models, API endpoints, edge cases).
3. Examine the provided Source Code files.
4. Author clean, executable Python test code using `unittest` or `pytest`.
5. Cover happy paths, boundary cases, and error conditions.
6. Make sure tests import the code modules directly (e.g. `from app import ...` or `from models import ...`).
7. Never use external network requests; mock network calls or external services if needed.
8. Output executable test code in test_file_content.

Return the result according to the provided schema.
"""
    )

    # Prepare file inventory for prompt
    files_context = "\n\n".join(
        [f"--- File: {f.get('path')} ---\n{f.get('content')}" for f in code_files]
    )

    human_prompt = imports.HumanMessage(
        content=f"""
=== REQUIREMENTS ===
{requirements}

=== DESIGN ===
{design}

=== SOURCE CODE FILES ===
{files_context}

Generate an independent verification test suite for this code.
"""
    )

    # 3. Generate verification test suite
    test_gen_result: TestSuiteGeneration = test_generator_llm.invoke([
        system_prompt,
        human_prompt
    ])

    test_files_to_run = {
        test_gen_result.test_file_name: test_gen_result.test_file_content
    }

    # 4. Execute the tests via the secure test_runner tool
    test_command = code_artifact.get("test_command", None)
    execution_result = run_code_tests(
        files=code_files,
        test_files=test_files_to_run,
        test_command=test_command,
        timeout_seconds=30
    )

    test_results_payload: dict = {
        "success": execution_result["success"],
        "total_tests": execution_result["total_tests"],
        "passed_tests": execution_result["passed_tests"],
        "failed_tests": execution_result["failed_tests"],
        "errors": execution_result["errors"],
        "raw_output": execution_result["raw_output"],
        "summary": execution_result["summary"],
        "duration_seconds": execution_result["duration_seconds"],
        "test_files": test_files_to_run
    }

    return {
        "test_results": test_results_payload,
        "test_version": state.get("test_version", 0) + 1,
        "current_stage": "test",
        "workflow_status": "running"
    }
